apiVersion: v1
kind: ImageStream
metadata:
  name: sso-oracle
spec:
  tags:
    - name: '1.0'
      annotations:
        version: '1.0'
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/redhat-sso-7/sso72-openshift:1.0'